services:
  - type: web
    name: mcp-server-100
    runtime: node
    region: singapore
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: MCP_TOKEN
        generateValue: true
      - key: API_KEY
        generateValue: true