name: CI

on:
  push:
    branches: [ 'master', 'main' ]
  pull_request:
    branches: [ 'master', 'main' ]
  workflow_dispatch: {}

jobs:
  build:
    name: Node.js CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Run lint (if present)
        run: |
          if grep -q '"lint"' package.json; then
            pnpm run lint
          else
            echo "No lint script found, skipping"
          fi

      - name: Build (TypeScript)
        run: pnpm run build

      - name: Run tests (if present)
        run: |
          if grep -q '"test"' package.json; then
            pnpm test
          else
            echo "No test script found, skipping"
          fi
